AlgoritmO "pares-consecutivos"

VaR
   X, i : InteirO
IniciO
   Escreva("Digite um número inteiro: ")
   Leia(X)
   
     EnquantO X <> 0 Faca
   
      Se X % 2 <> 0 entao
         X <-  X + 1
      FimSe
      
      soma <- 5 * x + 20
      
      EscrevaL("SOMA = ", soma)
      
      Escreva("Digite um número inteiro: ")
      Leia(X)
      
   FimEnquantO

FimAlgoritmO
