AlgoritmO "media-ponderada"

VaR
   n, i : InteirO
   a, b, c, media : ReaL

IniciO

      Escreva("Quantos casos você vai digitar? ")
      Leia(N)
      
      Para i de 1 ate N Faca
      
        EscrevaL("Digite três números: ")
        Leia(a)
        Leia(b)
        Leia(c)
        
        media <- (a * 2 + b * 3 + c * 5) / 10)
        EscrevaL("MÉDIA = ", media:3:1)


       FimPara

FimAlgoritmO
