AlgoritmO "funcoesMatematicas2"

VaR
   x, y, z, a, b, c, d : ReaL
IniciO
      x <- 2.0
      y <- 3.0
      z <- -7.0

      a <- Exp(x, y)
      b <- RaizQ(y)
      c <- Pi
      d <- Abs(z)

      EscrevaL("O número elevado ao quadrado é:" ,a)
      EscrevaL

      EscrevaL("A raiz quadrada é:" ,b)
      EscrevaL

      EscrevaL("O número irracional é:" ,c)
      EscrevaL

      EscrevaL("O número absoluto é:" ,d)
      
FimAlgoritmO
