AlgoritmO "notas"

VaR

   nota1, nota2, media : ReaL

IniciO
      Escreva("Digite a primeira nota: ")
      Leia(nota1)
      
      Escreva("Digite a segunda nota: ")
      Leia (nota2)
      
      media <- nota1 + nota2
      
      EscrevaL("NOTA FINAL = ",media:3:1)
      EscrevaL
      
      Se media >= 60 entao
         Escreva("O aluno está aprovado!")
      Senao
           Escreva("O aluno está reprovado!")
      FimSe

FimAlgoritmO
