AlgoritmO "problema"

VaR
      N, i : InteirO
      vet : vetor [0..9] de ReaL
IniciO

      Escreva("Quantos números você vai digitar?")
      Leia(N)
      
      Para i de 0 AtE N-1 Faca
           Escreva("Digite um número: ")
           Leia(vet[i])
      
      FimPara
      
      EscrevaL
      EscrevaL("NÚMEROS DIGITADOS:")
      
      Para i de 0 AtE N-1 Faca
           EscrevaL(vet[i])
      FimPara

FimAlgoritmO
