AlgoritmO "soma"

VaR
    X, Y, soma : InteirO
IniciO
    Escreva("Digite o valor de X:")
    Leia(X)

    Escreva("Digite o valor de Y:")
    Leia(Y)
    
    soma <- X + Y
    
    EscrevaL("SOMA = ",soma:1:0)

    EscrevaL
    
    Escreva("Digite o valor de X:")
    Leia(X)
    
    Escreva("Digite o valor de Y:")
    Leia(Y)
    
    soma <- X + Y
    
    Escreva("SOMA = ",soma:1:0)

FimAlgoritmO
