AlgoritmO "terreno"

VaR

   largura, comprimento, metroQuadrado, area, preco : real
   
IniciO

    Escreva("Digite a largura do terreno: ")
    Leia(largura)
    Escreva("Digite o comprimento: ")
    Leia(comprimento)
    Escreva("Digite o metro quadrado: ")
    Leia(metroQuadrado)

    area <- largura * comprimento
    preco <- largura * metroQuadrado

    EscrevaL("Área do terreno = ", area:8:2)
    EscrevaL("Preço do terreno = ",preco:8:2)

FimAlgoritmO


